// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the accounts table.
    /// </summary>
	[ModuleProperty(ModuleName = "Accounts", TableName="accounts")]
	public partial class Account : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "modified_user_id")]
		public virtual string ModifiedUserId { get; set; }

		[JsonProperty(PropertyName = "created_by")]
		public virtual string CreatedBy { get; set; }

		[JsonProperty(PropertyName = "description")]
		public virtual string Description { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

		[JsonProperty(PropertyName = "account_type")]
		public virtual string AccountType { get; set; }

		[JsonProperty(PropertyName = "industry")]
		public virtual string Industry { get; set; }

		[JsonProperty(PropertyName = "annual_revenue")]
		public virtual string AnnualRevenue { get; set; }

		[JsonProperty(PropertyName = "phone_fax")]
		public virtual string PhoneFax { get; set; }

		[JsonProperty(PropertyName = "billing_address_street")]
		public virtual string BillingAddressStreet { get; set; }

		[JsonProperty(PropertyName = "billing_address_city")]
		public virtual string BillingAddressCity { get; set; }

		[JsonProperty(PropertyName = "billing_address_state")]
		public virtual string BillingAddressState { get; set; }

		[JsonProperty(PropertyName = "billing_address_postalcode")]
		public virtual string BillingAddressPostalcode { get; set; }

		[JsonProperty(PropertyName = "billing_address_country")]
		public virtual string BillingAddressCountry { get; set; }

		[JsonProperty(PropertyName = "rating")]
		public virtual string Rating { get; set; }

		[JsonProperty(PropertyName = "phone_office")]
		public virtual string PhoneOffice { get; set; }

		[JsonProperty(PropertyName = "phone_alternate")]
		public virtual string PhoneAlternate { get; set; }

		[JsonProperty(PropertyName = "website")]
		public virtual string Website { get; set; }

		[JsonProperty(PropertyName = "ownership")]
		public virtual string Ownership { get; set; }

		[JsonProperty(PropertyName = "employees")]
		public virtual string Employees { get; set; }

		[JsonProperty(PropertyName = "ticker_symbol")]
		public virtual string TickerSymbol { get; set; }

		[JsonProperty(PropertyName = "shipping_address_street")]
		public virtual string ShippingAddressStreet { get; set; }

		[JsonProperty(PropertyName = "shipping_address_city")]
		public virtual string ShippingAddressCity { get; set; }

		[JsonProperty(PropertyName = "shipping_address_state")]
		public virtual string ShippingAddressState { get; set; }

		[JsonProperty(PropertyName = "shipping_address_postalcode")]
		public virtual string ShippingAddressPostalcode { get; set; }

		[JsonProperty(PropertyName = "shipping_address_country")]
		public virtual string ShippingAddressCountry { get; set; }

		[JsonProperty(PropertyName = "parent_id")]
		public virtual string ParentId { get; set; }

		[JsonProperty(PropertyName = "sic_code")]
		public virtual string SicCode { get; set; }

		[JsonProperty(PropertyName = "campaign_id")]
		public virtual string CampaignId { get; set; }

	}
}