// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the campaign_log table.
    /// </summary>
	[ModuleProperty(ModuleName = "CampaignLog", TableName="campaign_log")]
	public partial class CampaignLog : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "campaign_id")]
		public virtual string CampaignId { get; set; }

		[JsonProperty(PropertyName = "target_tracker_key")]
		public virtual string TargetTrackerKey { get; set; }

		[JsonProperty(PropertyName = "target_id")]
		public virtual string TargetId { get; set; }

		[JsonProperty(PropertyName = "target_type")]
		public virtual string TargetType { get; set; }

		[JsonProperty(PropertyName = "activity_type")]
		public virtual string ActivityType { get; set; }

		[JsonProperty(PropertyName = "activity_date")]
		public virtual DateTime? ActivityDate { get; set; }

		[JsonProperty(PropertyName = "related_id")]
		public virtual string RelatedId { get; set; }

		[JsonProperty(PropertyName = "related_type")]
		public virtual string RelatedType { get; set; }

		[JsonProperty(PropertyName = "archived")]
		public virtual sbyte? Archived { get; set; }

		[JsonProperty(PropertyName = "hits")]
		public virtual int? Hits { get; set; }

		[JsonProperty(PropertyName = "list_id")]
		public virtual string ListId { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "more_information")]
		public virtual string MoreInformation { get; set; }

		[JsonProperty(PropertyName = "marketing_id")]
		public virtual string MarketingId { get; set; }

	}
}