// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the cron_remove_documents table.
    /// </summary>
	[ModuleProperty(ModuleName = "CronRemoveDocuments", TableName="cron_remove_documents")]
	public partial class CronRemoveDocuments : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "bean_id")]
		public virtual string BeanId { get; set; }

		[JsonProperty(PropertyName = "module")]
		public virtual string Module { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

	}
}