// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the folders_rel table.
    /// </summary>
	[ModuleProperty(ModuleName = "FoldersRel", TableName="folders_rel")]
	public partial class FoldersRel : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "folder_id")]
		public virtual string FolderId { get; set; }

		[JsonProperty(PropertyName = "polymorphic_module")]
		public virtual string PolymorphicModule { get; set; }

		[JsonProperty(PropertyName = "polymorphic_id")]
		public virtual string PolymorphicId { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}