// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the job_queue table.
    /// </summary>
	[ModuleProperty(ModuleName = "JobQueue", TableName="job_queue")]
	public partial class JobQueue : EntityBase
	{
		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "scheduler_id")]
		public virtual string SchedulerId { get; set; }

		[JsonProperty(PropertyName = "execute_time")]
		public virtual DateTime? ExecuteTime { get; set; }

		[JsonProperty(PropertyName = "status")]
		public virtual string Status { get; set; }

		[JsonProperty(PropertyName = "resolution")]
		public virtual string Resolution { get; set; }

		[JsonProperty(PropertyName = "message")]
		public virtual string Message { get; set; }

		[JsonProperty(PropertyName = "target")]
		public virtual string Target { get; set; }

		[JsonProperty(PropertyName = "data")]
		public virtual string Data { get; set; }

		[JsonProperty(PropertyName = "requeue")]
		public virtual sbyte? Requeue { get; set; }

		[JsonProperty(PropertyName = "retry_count")]
		public virtual sbyte? RetryCount { get; set; }

		[JsonProperty(PropertyName = "failure_count")]
		public virtual sbyte? FailureCount { get; set; }

		[JsonProperty(PropertyName = "job_delay")]
		public virtual int? JobDelay { get; set; }

		[JsonProperty(PropertyName = "client")]
		public virtual string Client { get; set; }

		[JsonProperty(PropertyName = "percent_complete")]
		public virtual int? PercentComplete { get; set; }

	}
}