// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the oauth_nonce table.
    /// </summary>
	[ModuleProperty(ModuleName = "OauthNonce", TableName="oauth_nonce")]
	public partial class OauthNonce : EntityBase
	{
		[JsonProperty(PropertyName = "conskey")]
		public virtual string Conskey { get; set; }

		[JsonProperty(PropertyName = "nonce")]
		public virtual string Nonce { get; set; }

		[JsonProperty(PropertyName = "nonce_ts")]
		public virtual long? NonceTs { get; set; }

	}
}