// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the relationships table.
    /// </summary>
	[ModuleProperty(ModuleName = "Relationships", TableName="relationships")]
	public partial class Relationship : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "relationship_name")]
		public virtual string RelationshipName { get; set; }

		[JsonProperty(PropertyName = "lhs_module")]
		public virtual string LhsModule { get; set; }

		[JsonProperty(PropertyName = "lhs_table")]
		public virtual string LhsTable { get; set; }

		[JsonProperty(PropertyName = "lhs_key")]
		public virtual string LhsKey { get; set; }

		[JsonProperty(PropertyName = "rhs_module")]
		public virtual string RhsModule { get; set; }

		[JsonProperty(PropertyName = "rhs_table")]
		public virtual string RhsTable { get; set; }

		[JsonProperty(PropertyName = "rhs_key")]
		public virtual string RhsKey { get; set; }

		[JsonProperty(PropertyName = "join_table")]
		public virtual string JoinTable { get; set; }

		[JsonProperty(PropertyName = "join_key_lhs")]
		public virtual string JoinKeyLhs { get; set; }

		[JsonProperty(PropertyName = "join_key_rhs")]
		public virtual string JoinKeyRhs { get; set; }

		[JsonProperty(PropertyName = "relationship_type")]
		public virtual string RelationshipType { get; set; }

		[JsonProperty(PropertyName = "relationship_role_column")]
		public virtual string RelationshipRoleColumn { get; set; }

		[JsonProperty(PropertyName = "relationship_role_column_value")]
		public virtual string RelationshipRoleColumnValue { get; set; }

		[JsonProperty(PropertyName = "reverse")]
		public virtual sbyte? Reverse { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}