// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the roles_modules table.
    /// </summary>
	[ModuleProperty(ModuleName = "RolesModules", TableName="roles_modules")]
	public partial class RolesModules : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "role_id")]
		public virtual string RoleId { get; set; }

		[JsonProperty(PropertyName = "module_id")]
		public virtual string ModuleId { get; set; }

		[JsonProperty(PropertyName = "allow")]
		public virtual sbyte? Allow { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}