// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarRestSharp.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the tracker table.
    /// </summary>
	[ModuleProperty(ModuleName = "Tracker", TableName="tracker")]
	public partial class Tracker : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual int Id { get; set; }

		[JsonProperty(PropertyName = "monitor_id")]
		public virtual string MonitorId { get; set; }

		[JsonProperty(PropertyName = "user_id")]
		public virtual string UserId { get; set; }

		[JsonProperty(PropertyName = "module_name")]
		public virtual string ModuleName { get; set; }

		[JsonProperty(PropertyName = "item_id")]
		public virtual string ItemId { get; set; }

		[JsonProperty(PropertyName = "item_summary")]
		public virtual string ItemSummary { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "action")]
		public virtual string Action { get; set; }

		[JsonProperty(PropertyName = "session_id")]
		public virtual string SessionId { get; set; }

		[JsonProperty(PropertyName = "visible")]
		public virtual sbyte? Visible { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}