// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the acl_roles_actions table.
    /// </summary>
	[ModuleProperty(ModuleName = "AclRolesActions", TableName="acl_roles_actions")]
	public partial class AclRolesActions : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "role_id")]
		public virtual string RoleId { get; set; }

		[JsonProperty(PropertyName = "action_id")]
		public virtual string ActionId { get; set; }

		[JsonProperty(PropertyName = "access_override")]
		public virtual int? AccessOverride { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}