// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the campaigns table.
    /// </summary>
	[ModuleProperty(ModuleName = "Campaigns", TableName="campaigns")]
	public partial class Campaign : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "modified_user_id")]
		public virtual string ModifiedUserId { get; set; }

		[JsonProperty(PropertyName = "created_by")]
		public virtual string CreatedBy { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

		[JsonProperty(PropertyName = "tracker_key")]
		public virtual int TrackerKey { get; set; }

		[JsonProperty(PropertyName = "tracker_count")]
		public virtual int? TrackerCount { get; set; }

		[JsonProperty(PropertyName = "refer_url")]
		public virtual string ReferUrl { get; set; }

		[JsonProperty(PropertyName = "tracker_text")]
		public virtual string TrackerText { get; set; }

		[JsonProperty(PropertyName = "start_date")]
		public virtual DateTime? StartDate { get; set; }

		[JsonProperty(PropertyName = "end_date")]
		public virtual DateTime? EndDate { get; set; }

		[JsonProperty(PropertyName = "status")]
		public virtual string Status { get; set; }

		[JsonProperty(PropertyName = "impressions")]
		public virtual int? Impressions { get; set; }

		[JsonProperty(PropertyName = "currency_id")]
		public virtual string CurrencyId { get; set; }

		[JsonProperty(PropertyName = "budget")]
		public virtual double? Budget { get; set; }

		[JsonProperty(PropertyName = "expected_cost")]
		public virtual double? ExpectedCost { get; set; }

		[JsonProperty(PropertyName = "actual_cost")]
		public virtual double? ActualCost { get; set; }

		[JsonProperty(PropertyName = "expected_revenue")]
		public virtual double? ExpectedRevenue { get; set; }

		[JsonProperty(PropertyName = "campaign_type")]
		public virtual string CampaignType { get; set; }

		[JsonProperty(PropertyName = "objective")]
		public virtual string Objective { get; set; }

		[JsonProperty(PropertyName = "content")]
		public virtual string Content { get; set; }

		[JsonProperty(PropertyName = "frequency")]
		public virtual string Frequency { get; set; }

	}
}