// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the config table.
    /// </summary>
	[ModuleProperty(ModuleName = "Config", TableName="config")]
	public partial class Config : EntityBase
	{
		[JsonProperty(PropertyName = "category")]
		public virtual string Category { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "value")]
		public virtual string Value { get; set; }

	}
}