// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the document_revisions table.
    /// </summary>
	[ModuleProperty(ModuleName = "DocumentRevisions", TableName="document_revisions")]
	public partial class DocumentRevisions : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "change_log")]
		public virtual string ChangeLog { get; set; }

		[JsonProperty(PropertyName = "document_id")]
		public virtual string DocumentId { get; set; }

		[JsonProperty(PropertyName = "doc_id")]
		public virtual string DocId { get; set; }

		[JsonProperty(PropertyName = "doc_type")]
		public virtual string DocType { get; set; }

		[JsonProperty(PropertyName = "doc_url")]
		public virtual string DocUrl { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "created_by")]
		public virtual string CreatedBy { get; set; }

		[JsonProperty(PropertyName = "filename")]
		public virtual string Filename { get; set; }

		[JsonProperty(PropertyName = "file_ext")]
		public virtual string FileExt { get; set; }

		[JsonProperty(PropertyName = "file_mime_type")]
		public virtual string FileMimeType { get; set; }

		[JsonProperty(PropertyName = "revision")]
		public virtual string Revision { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

	}
}