// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the eapm table.
    /// </summary>
	[ModuleProperty(ModuleName = "Eapm", TableName="eapm")]
	public partial class Eapm : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "modified_user_id")]
		public virtual string ModifiedUserId { get; set; }

		[JsonProperty(PropertyName = "created_by")]
		public virtual string CreatedBy { get; set; }

		[JsonProperty(PropertyName = "description")]
		public virtual string Description { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

		[JsonProperty(PropertyName = "password")]
		public virtual string Password { get; set; }

		[JsonProperty(PropertyName = "url")]
		public virtual string Url { get; set; }

		[JsonProperty(PropertyName = "application")]
		public virtual string Application { get; set; }

		[JsonProperty(PropertyName = "api_data")]
		public virtual string ApiData { get; set; }

		[JsonProperty(PropertyName = "consumer_key")]
		public virtual string ConsumerKey { get; set; }

		[JsonProperty(PropertyName = "consumer_secret")]
		public virtual string ConsumerSecret { get; set; }

		[JsonProperty(PropertyName = "oauth_token")]
		public virtual string OauthToken { get; set; }

		[JsonProperty(PropertyName = "oauth_secret")]
		public virtual string OauthSecret { get; set; }

		[JsonProperty(PropertyName = "validated")]
		public virtual sbyte? Validated { get; set; }

	}
}