// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the email_cache table.
    /// </summary>
	[ModuleProperty(ModuleName = "EmailCache", TableName="email_cache")]
	public partial class EmailCache : EntityBase
	{
		[JsonProperty(PropertyName = "ie_id")]
		public virtual string IeId { get; set; }

		[JsonProperty(PropertyName = "mbox")]
		public virtual string Mbox { get; set; }

		[JsonProperty(PropertyName = "subject")]
		public virtual string Subject { get; set; }

		[JsonProperty(PropertyName = "fromaddr")]
		public virtual string Fromaddr { get; set; }

		[JsonProperty(PropertyName = "toaddr")]
		public virtual string Toaddr { get; set; }

		[JsonProperty(PropertyName = "senddate")]
		public virtual DateTime? Senddate { get; set; }

		[JsonProperty(PropertyName = "message_id")]
		public virtual string MessageId { get; set; }

		[JsonProperty(PropertyName = "mailsize")]
		public virtual uint? Mailsize { get; set; }

		[JsonProperty(PropertyName = "imap_uid")]
		public virtual uint? ImapUid { get; set; }

		[JsonProperty(PropertyName = "msgno")]
		public virtual uint? Msgno { get; set; }

		[JsonProperty(PropertyName = "recent")]
		public virtual sbyte? Recent { get; set; }

		[JsonProperty(PropertyName = "flagged")]
		public virtual sbyte? Flagged { get; set; }

		[JsonProperty(PropertyName = "answered")]
		public virtual sbyte? Answered { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "seen")]
		public virtual sbyte? Seen { get; set; }

		[JsonProperty(PropertyName = "draft")]
		public virtual sbyte? Draft { get; set; }

	}
}