// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the emails_text table.
    /// </summary>
	[ModuleProperty(ModuleName = "EmailsText", TableName="emails_text")]
	public partial class EmailsText : EntityBase
	{
		[JsonProperty(PropertyName = "email_id")]
		public virtual string EmailId { get; set; }

		[JsonProperty(PropertyName = "from_addr")]
		public virtual string FromAddr { get; set; }

		[JsonProperty(PropertyName = "reply_to_addr")]
		public virtual string ReplyToAddr { get; set; }

		[JsonProperty(PropertyName = "to_addrs")]
		public virtual string ToAddrs { get; set; }

		[JsonProperty(PropertyName = "cc_addrs")]
		public virtual string CcAddrs { get; set; }

		[JsonProperty(PropertyName = "bcc_addrs")]
		public virtual string BccAddrs { get; set; }

		[JsonProperty(PropertyName = "description")]
		public virtual string Description { get; set; }

		[JsonProperty(PropertyName = "description_html")]
		public virtual string DescriptionHtml { get; set; }

		[JsonProperty(PropertyName = "raw_source")]
		public virtual string RawSource { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}