// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the emails_email_addr_rel table.
    /// </summary>
	[ModuleProperty(ModuleName = "EmailsEmailAddrRel", TableName="emails_email_addr_rel")]
	public partial class EmailsEmailAddrRel : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "email_id")]
		public virtual string EmailId { get; set; }

		[JsonProperty(PropertyName = "address_type")]
		public virtual string AddressType { get; set; }

		[JsonProperty(PropertyName = "email_address_id")]
		public virtual string EmailAddressId { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}