// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the import_maps table.
    /// </summary>
	[ModuleProperty(ModuleName = "ImportMaps", TableName="import_maps")]
	public partial class ImportMaps : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "source")]
		public virtual string Source { get; set; }

		[JsonProperty(PropertyName = "enclosure")]
		public virtual string Enclosure { get; set; }

		[JsonProperty(PropertyName = "delimiter")]
		public virtual string Delimiter { get; set; }

		[JsonProperty(PropertyName = "module")]
		public virtual string Module { get; set; }

		[JsonProperty(PropertyName = "content")]
		public virtual string Content { get; set; }

		[JsonProperty(PropertyName = "default_values")]
		public virtual string DefaultValues { get; set; }

		[JsonProperty(PropertyName = "has_header")]
		public virtual sbyte? HasHeader { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

		[JsonProperty(PropertyName = "is_published")]
		public virtual string IsPublished { get; set; }

	}
}