// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the inbound_email_cache_ts table.
    /// </summary>
	[ModuleProperty(ModuleName = "InboundEmailCacheTs", TableName="inbound_email_cache_ts")]
	public partial class InboundEmailCacheTs : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "ie_timestamp")]
		public virtual uint? IeTimestamp { get; set; }

	}
}