// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the inbound_email table.
    /// </summary>
	[ModuleProperty(ModuleName = "InboundEmail", TableName="inbound_email")]
	public partial class InboundEmail : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

		[JsonProperty(PropertyName = "date_entered")]
		public virtual DateTime? DateEntered { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "modified_user_id")]
		public virtual string ModifiedUserId { get; set; }

		[JsonProperty(PropertyName = "created_by")]
		public virtual string CreatedBy { get; set; }

		[JsonProperty(PropertyName = "name")]
		public virtual string Name { get; set; }

		[JsonProperty(PropertyName = "status")]
		public virtual string Status { get; set; }

		[JsonProperty(PropertyName = "server_url")]
		public virtual string ServerUrl { get; set; }

		[JsonProperty(PropertyName = "email_user")]
		public virtual string EmailUser { get; set; }

		[JsonProperty(PropertyName = "email_password")]
		public virtual string EmailPassword { get; set; }

		[JsonProperty(PropertyName = "port")]
		public virtual int? Port { get; set; }

		[JsonProperty(PropertyName = "service")]
		public virtual string Service { get; set; }

		[JsonProperty(PropertyName = "mailbox")]
		public virtual string Mailbox { get; set; }

		[JsonProperty(PropertyName = "delete_seen")]
		public virtual sbyte? DeleteSeen { get; set; }

		[JsonProperty(PropertyName = "mailbox_type")]
		public virtual string MailboxType { get; set; }

		[JsonProperty(PropertyName = "template_id")]
		public virtual string TemplateId { get; set; }

		[JsonProperty(PropertyName = "stored_options")]
		public virtual string StoredOptions { get; set; }

		[JsonProperty(PropertyName = "group_id")]
		public virtual string GroupId { get; set; }

		[JsonProperty(PropertyName = "is_personal")]
		public virtual sbyte? IsPersonal { get; set; }

		[JsonProperty(PropertyName = "groupfolder_id")]
		public virtual string GroupfolderId { get; set; }

	}
}