// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the oauth_tokens table.
    /// </summary>
	[ModuleProperty(ModuleName = "OauthTokens", TableName="oauth_tokens")]
	public partial class OauthTokens : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "secret")]
		public virtual string Secret { get; set; }

		[JsonProperty(PropertyName = "tstate")]
		public virtual string Tstate { get; set; }

		[JsonProperty(PropertyName = "consumer")]
		public virtual string Consumer { get; set; }

		[JsonProperty(PropertyName = "token_ts")]
		public virtual long? TokenTs { get; set; }

		[JsonProperty(PropertyName = "verify")]
		public virtual string Verify { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte Deleted { get; set; }

		[JsonProperty(PropertyName = "callback_url")]
		public virtual string CallbackUrl { get; set; }

		[JsonProperty(PropertyName = "assigned_user_id")]
		public virtual string AssignedUserId { get; set; }

	}
}