// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the opportunities_contacts table.
    /// </summary>
	[ModuleProperty(ModuleName = "OpportunitiesContacts", TableName="opportunities_contacts")]
	public partial class OpportunitiesContacts : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "contact_id")]
		public virtual string ContactId { get; set; }

		[JsonProperty(PropertyName = "opportunity_id")]
		public virtual string OpportunityId { get; set; }

		[JsonProperty(PropertyName = "contact_role")]
		public virtual string ContactRole { get; set; }

		[JsonProperty(PropertyName = "date_modified")]
		public virtual DateTime? DateModified { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}