// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace SugarCrm.RestApiCalls.Models
{
	using System;
	using Newtonsoft.Json;
	

    /// <summary>
    /// A class which represents the users_password_link table.
    /// </summary>
	[ModuleProperty(ModuleName = "UsersPasswordLink", TableName="users_password_link")]
	public partial class UsersPasswordLink : EntityBase
	{
		[JsonProperty(PropertyName = "id")]
		public virtual string Id { get; set; }

		[JsonProperty(PropertyName = "username")]
		public virtual string Username { get; set; }

		[JsonProperty(PropertyName = "date_generated")]
		public virtual DateTime? DateGenerated { get; set; }

		[JsonProperty(PropertyName = "deleted")]
		public virtual sbyte? Deleted { get; set; }

	}
}